services:
  # Rust Runner - 最簡化版本
  rust-runner:
    image: myoung34/github-runner:latest
    container_name: rust-runner
    restart: unless-stopped
    environment:
      - REPO_URL=https://github.com/allenneverland/backtest-server
      - ACCESS_TOKEN=${ACCESS_TOKEN}
      - RUNNER_NAME=rust-runner
      - RUNNER_LABELS=rust,cargo,backend,linux,x64
      - RUNNER_GROUP=default
      - RUNNER_WORK_DIRECTORY=/tmp/runner/work
      # 預設安裝工具
      - DISABLE_AUTO_UPDATE=true
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - rust_runner_data:/tmp/runner
      - ./install-tools.sh:/usr/local/bin/install-tools.sh:ro
    # 不覆蓋 entrypoint，使用原始啟動流程
    shm_size: '2gb'

  # Python & React Runner - 最簡化版本
  python-react-runner:
    image: myoung34/github-runner:latest
    container_name: python-react-runner
    restart: unless-stopped
    environment:
      - REPO_URL=https://github.com/allenneverland/stratplat-web-server
      - ACCESS_TOKEN=${ACCESS_TOKEN}
      - RUNNER_NAME=python-react-runner
      - RUNNER_LABELS=python,react,nodejs,web,linux,x64
      - RUNNER_GROUP=default
      - RUNNER_WORK_DIRECTORY=/tmp/runner/work
      - DISABLE_AUTO_UPDATE=true
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - python_react_runner_data:/tmp/runner
      - ./install-tools.sh:/usr/local/bin/install-tools.sh:ro
    shm_size: '2gb'

volumes:
  rust_runner_data:
  python_react_runner_data: